# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quotes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for quotes
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.9'
  pod 'Crashlytics', '~> 3.10.5'
  pod 'Firebase/Firestore'

  target 'quotes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'quotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'quotes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for quotes-tvOS
end
